#!/usr/bin/env python
import pika
import sys

connection = pika.BlockingConnection(
    pika.ConnectionParameters(host='localhost'))
channel = connection.channel()

channel.queue_declare(queue='taskqueue2')

msgBody =  'HOLA'

properties = pika.BasicProperties(content_type='application/json', delivery_mode=1, priority=1, content_encoding='utf-8')

channel.basic_publish(
    exchange='',
    routing_key='taskqueue2',
    body=msgBody,
    properties= properties
    )


print(" [x] Sent %r" % msgBody)
connection.close()
